export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDes: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transactions with zero fees",
  description: 'Get Access to our exclusive app that allow youto send unlimited transactions without getting charged any fees',
  buttonLabel: "Get Started",
  imgStart: false,
  img: require('../../images/svg-1.svg'),
  altTag: 'car',
  dark: true,
  primary: true,
  darkText: false,
}